### ISSUE TITLE
WebPack Support

### ISSUE THREAD

**Issue by go4cas** [genadis/aurelia-mdl#10]
Are there any plans to support webpack (NPM)?

**Comment by genadis** [comment]
I've uploaded the package to npm: [aurelia-mdl](https://www.npmjs.com/package/aurelia-mdl).

I'm not using WebPack though.

**Comment by cawomo** [comment]
@go4cas any luck implementing this with webpack?

**Comment by genadis** [comment]
I'm working with JSPM. The plugin compiles to amd. It's dependency [encapsulated-mdl](https://github.com/genadis/encapsulated-mdl) is [UMD](https://github.com/umdjs/umd) compliant, so it should be just a matter of configuring it right.

Not strictly related but check out my last comment in Issue #12 

If you make it work, I don't mind adding support for easier integration based on your input.

Thanks!

**Comment by cawomo** [comment]
@genadis thanks for the specification. I'm trying to get it to work, however I'm still missing something as I'm continuously getting the following stacktrace:

```
Unhandled rejection Error: Cannot find module './aurelia-mdl/mdl'.
    at webpackContextResolve (http://localhost:9000/app.bundle.js:10663:9)
    at webpackContext (http://localhost:9000/app.bundle.js:10658:29)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15702:48
```

Which leads me to think webpack can't resolve the plugin's following line:

`config.globalResources('./mdl');`

any ideas on how to fix this? so far I have added:

**to webpack.config.js**

```
entry: {
        'app': [/* this is filled by the aurelia-webpack-plugin */],
        'aurelia-bootstrap': coreBundles.bootstrap,
        'aurelia': coreBundles.aurelia.filter(pkg => coreBundles.bootstrap.indexOf(pkg) === -1),
        'material-mdl': ['aurelia-mdl']
    },
```

**to package.json**

```
"aurelia": {
    "build": {
      "resources": [
        {
          "bundle": "material-mdl",
          "path": "../node_modules/aurelia-mdl/dist/amd"
        }
      ]
    }
  },
```

Thanks!

**Comment by cawomo** [comment]
@genadis can you upload encapsulated-mdl to npm? it would help alot.

thanks!

**Comment by genadis** [comment]
@cawomo uploaded see #12 (old issue I know, sorry don't have much time lately)

But I've noticed there is [aurelia-mdl-webpack](https://www.npmjs.com/package/aurelia-mdl-webpack), so you probably better to use it.
