### ISSUE TITLE
Issue when rendering mdl-layout

### ISSUE THREAD

**Issue by casalot** [genadis/aurelia-mdl#2]
I have changed the code in the `nav-bar.html` of the Aurelia Skeleton Navigation project to:

``` html
<template bindable="router">
  <div mdl="layout" class="mdl-layout--fixed-header">
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">${router.title}</span>
        <div class="mdl-layout-spacer"></div>
      </div>
    </header>
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title">Title</span>
      <nav class="mdl-navigation">
        <ul>
          <li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">
            <a data-toggle="collapse" data-target="#skeleton-navigation-navbar-collapse.in" href.bind="row.href">${row.title}</a>
          </li>
        </ul>
      </nav>
    </div>
    <main class="mdl-layout__content">
      <div class="page-content page-host">
        <router-view></router-view>
      </div>
    </main>
  </div>
</template>
```

But, when rendering, I am seeing the following issues:
- The collapsed drawer menu does not display the hamburger icon, but instead the word menu.
- When opening the menu, and then clicking on on the links, the app navigates correctly to the selected route, and the correct content is displayed. But, the drawer menu does not close automatically. Is there any settings and/or code that I've missed?

Then I would also like to understand the following:
- Is the roboto font included by default when installing the aurelia-mdl jspm package?
- Are the mdl icons included by default when installing the aurelia-mdl jspm package?

If I use your code snippet from the README:

``` html
<button mdl="button" class="mdl-button--fab mdl-button--colored">
  <i class="material-icons">add</i>
</button>
```

it displays the mdl-fab button, but instead of rendering an icon on the button, the text "add" is displayed.

**Comment by casalot** [comment]
I have manually added the Roboto font, by including this into the `index.html` file:

``` html
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
```

The font is now used by the MDL stylesheet.

I have added the material-design-icons package using NPM, but no luck.

**Comment by genadis** [comment]
- Not sure I understand the question - drawer menu would display what you put in the html, in your case `Title` with navigation routes. if you want a logo, add something like:

```
    <div class="mdl-layout__drawer">
      <div class="mdl-layout__title"><img src="/images/logo.png"></div>
      <!-- ..... -->
    </div>
```
- Drawer closing - You didn't miss anything, it's MDL issue. It doesn't have implementation of dynamically closing the drawer. Notice that in all their demos they navigate to different URL and re render the whole page.
  One of the reasons I've included the `events`, so you can hook up and add your own functionality.
  Actually the Drawer issue is was one of the more complex, most of the stuff works without any issues.

To solve the drawer issue you can add to your `App` something like:

```
  constructor(eventAggregator) {
    // .......
    this.eventAggregator = eventAggregator;
    this.eventAggregator.subscribe('mdl:component:upgrade', this.mdlUpgradeHandler.bind(this));

    /* hide drawer when Aurelia router completes the navigation (there are bunch of events the router publishes you can use */
    this.eventAggregator.subscribe('router:navigation:complete', payload => {
      this.hideDrawer();
    });
  }

  mdlUpgradeHandler(payload) {
    if (payload.data.MaterialLayout) {
      this.mdlLayout = payload.data.MaterialLayout;  // This is the upgrade object MDL adds to DOM layout element
    }
  }

  /* Notice I use jQuery for hasClass, you of course don't have to.
   * MDL adds "'is-visible" class to the drawer DOM element when it is open.
  */
  hideDrawer() {
    if (this.mdlLayout && this.mdlLayout.drawer_ && $(this.mdlLayout.drawer_).hasClass('is-visible')) {
      this.mdlLayout.drawerToggleHandler_(); //drawerToggleHandler_() is MDL method
    }
  }
```
- roboto fonts and material-icons are not included by default because it's not mandatory for MDL.

Add it if you need:

```
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
```

**Comment by casalot** [comment]
Awesome! Manually adding the Robot font and the MD Icons, have now sorted out my display issues.

I'll try your suggestion for the drawer auto-close.

Thanks for the very quick response, and this is an awesome plug-in!

**Comment by genadis** [comment]
np,
Most of the credit for the plugin goes to: [redpelicans/aurelia-material](https://github.com/redpelicans/aurelia-material).
I just patched things up and added some stuff.

[encapsulate-mdl](https://github.com/genadis/encapsulated-mdl) was the real challenge for me.

**Comment by casalot** [comment]
@genadis, I've taken a bit of a different approach (got some guidance from StackOverflow). I've added a `nav-bar.js` View Model:

``` javascript
import {bindable} from 'aurelia-framework';

export class NavBar {
  @bindable router;
  toggleDrawer(route) {
    this.router.navigate(route);
    var drawer = document.getElementsByClassName('mdl-layout__drawer')[0];
    var obfuscator = document.getElementsByClassName('mdl-layout__obfuscator')[0];
    drawer.classList.remove('is-visible');
    obfuscator.classList.remove('is-visible');  }
}
```

Then in `app.html`, I've changed the `require` tag to:

``` html
<require from="nav-bar"></require>
```

And, finally adding `delegate` in the `nav-bar.html` view:

``` html
<a repeat.for="row of router.navigation" class="${row.isActive ? 'active-menu' : ''} mdl-navigation__link" href.bind="row.href" click.delegate="$parent.toggleDrawer(row.href)">${row.title}</a>
```

Working like a charm!

**Comment by genadis** [comment]
Glad it works for you!

A few notes:
- `drawerToggleHandler_` internaly calls `toggleDrawer` which does exactly what you are doing, I preferred the function way, in case MDL would add some additional logic to drawer toggling in the feature.
- I used the `router:navigation:complete` instead of link click because it fires up after the navigation is actually completed (success or error) and not when it is started, so it gives you opportunity to show nice progress animation inside the drawer while navigating. 
- custom element for nav-bar is always a good idea :)

It all depends on your use case...
Good luck with your project!

**Comment by casalot** [comment]
Should the code you suggested be added to the `app.js`?

**Comment by casalot** [comment]
I've got it working now, thanks. I've added it to the `nav-bar.js`.

``` javascript
import {bindable} from 'aurelia-framework';
import {inject} from 'aurelia-framework';
import {EventAggregator} from 'aurelia-event-aggregator';

@inject(EventAggregator)

export class NavBar {
  @bindable router;
  constructor(eventAggregator) {
    this.eventAggregator = eventAggregator;
    this.eventAggregator.subscribe('mdl:component:upgrade', this.mdlUpgradeHandler.bind(this));
    this.eventAggregator.subscribe('router:navigation:complete', payload => {
      this.hideDrawer();
    });
  }

  mdlUpgradeHandler(payload) {
    if (payload.data.MaterialLayout) {
      this.mdlLayout = payload.data.MaterialLayout;
    }
  }
  hideDrawer() {
    if (this.mdlLayout && this.mdlLayout.drawer_ && this.mdlLayout.drawer_.classList.contains('is-visible')) {
      this.mdlLayout.drawerToggleHandler_();
    }
  }
}
```
