### ISSUE TITLE
Timeout on Snackbar

### ISSUE THREAD

**Issue by go4cas** [genadis/aurelia-mdl#3]
Is it possible to set a custom `timeout` value on the snackbar element?

**Comment by genadis** [comment]
According to: http://www.getmdl.io/components/snackbar/index.html there is (haven't tested it)
Instead of query selector you can use [ref](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.8/doc/article/cheat-sheet/5) to get the DOM element.

**Comment by go4cas** [comment]
I was hoping to have it as a bindable property in the View Model, and then being able to set it as an attribute on the element in the view.

**Comment by genadis** [comment]
The current implementation is as custom attribute, basically it only turns the static MDL into dynamic by  upgrading elements as they are added.
It doesn't implement any specific function per MDL component type.

I think if you wanted that, custom elements can be implemented on top  of the generic custom attribute and added to the plugin.
For example for the snackbar as:

```
<mdl-snackbar timeout.bind="myTimeout"></mdl-snackbar>
```

The `mdl-snackbar` could use the mdl custom attribute internally.
