### ISSUE TITLE
Using different icon sets

### ISSUE THREAD

**Issue by egeland** [genadis/aurelia-mdl#4]
Probably something easy, but I'm not sure what I'm doing wrong..

I have loaded the ['mdi' icon set](https://materialdesignicons.com/) - because there are more icons than the official MD icon set by Google - and if I use them in my page, it works ok.

However, the aurelia-mdl 'layout' tries to use the (unavailable) standard menu icon and just shows "_menu_" rather than an icon.
How could I get the correct icon in there?
I'm trying this:

```
<template bindable="router">
  <div mdl="layout">
    <header class="mdl-layout__header">
      <i class="mdl-layout-icon mdi mdi-menu"></i>
      <div class="mdl-layout__header-row">
      ...
```

With MDI, to show the icon elsewhere, it'd just be `<i class="mdi mdi-icon"></i>` but if I just put that somewhere, it just appears in the wrong place, and the actual menu icon spot still has the broken behaviour. The above snippet gives me no new icon, and still broken behaviour.

Any hints? :confounded:

**Comment by egeland** [comment]
Just played a little more, and tried this, which worked! :

```
<template bindable="router">
  <div mdl="layout">
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <div class="mdl-layout__drawer-button"><i class="mdi mdi-menu"></i></div>
        <!-- Title -->
        ...
```

**Comment by genadis** [comment]
You could also use something like:

```
<template bindable="router">
  <div mdl="layout">
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <!-- .... -->
      </div>
    </header>

    <div class="mdl-layout__drawer">
         <!-- ... -->
         <div class="mdl-layout__drawer-button"><i class="mdi mdi-menu"></i></div>
    </div>
     ....
```

Check out the MDL examples of [navigation layout](http://www.getmdl.io/components/index.html#layout-section/layout)

**Comment by egeland** [comment]
Yeah, that spot makes more sense, given the class names.. :+1:
