### ISSUE TITLE
Question: How to put a tooltip in a repeat

### ISSUE THREAD

**Issue by egeland** [genadis/aurelia-mdl#6]
I'm trying to get a tooltip to show on each button for items in an array, that are iterated by a `repeat.for`.

The MDL docs have a simplistic example of a tooltip being `for="id-of-thing"`, but if I put that in my `repeat` I either get only a tooltip on the first item (if the `id` is a static name like `editbutton`, or **no** tooltip, if I try dynamic `id` generation like below)

```
<div class="mdl-list" click.delegate="handleClick($event)" style="height: 100%;">
     <div class="mdl-list__item" repeat.for="entry of taskList" style="height: 56px;">

          <span class="mdl-list__item-primary-content">
            ${entry.name}
          </span>

          <span class="mdl-list__item-secondary-action">
            <button id="editbutton-${$index}" mdl="button" class="mdl-button--icon mdl-button--colored">
              <i class="mdi mdi-pencil"></i>
            </button>
            <div mdl="tooltip" class="mdl-tooltip--right" for="editbutton-${$index}">
              Edit Task
            </div>
          </span>
 ...
```

Any ideas?

And also, I can only seem to get `mdl-tooltip--large` to work, the `--right` in the above code does not put the tooltip on the right..

**Comment by genadis** [comment]
Please Notice, Aurelia has an [issue](https://github.com/aurelia/templating-binding/issues/64) with using `for` attribute on non `<label>`.
 For menu element you can use `data-mdl-for` attribute instead of `for`. But for tooltips MDL didn't implement it, so if you use binding/string interpolation, until the Aurelia bug is fixed, use `label` as in the example below.

Allow me to suggest wrapping it in custom element.
I'm successfully using it as:

```
// button-icon.html
<template bindable="click" bindable="tooltipEn">
  <div click.delegate="clickHandle($event)" mdl="button" class="mdl-js-ripple-effect mdl-button--icon" id="button-${id}">
    <i class="material-icons md-dark">
      <template replaceable part="icon">&#xE913;</template> <!--touch_app-->
    </i>
  </div>

  <label if.bind="tooltipEn" mdl="tooltip" class="mdl-tooltip--large" for="button-${id}">
    <template replaceable part="tooltip">click</template>
  </label>
</template>
```

```
// button-icon.js
import {bindable, customElement} from 'aurelia-framework';
import {guid} from '../util';

@customElement('button-icon')
export class ButtonIcon {
  id = guid();      // generate unique guid
  @bindable tooltipEn = false;
  @bindable click;

  clickHandle(e) {
    if (typeof this.click === 'function') {
      this.click({event: e});
    }
  }
}
```

Usage:

```
        <button-icon click.call="myClickAction()" tooltip-en.one-way="enableTooltip">
          <template replace-part="icon">&#xE879;</template> <!--exit_to_app-->
          <template replace-part="tooltip">This is my tool tip</template>
        </button-icon>
```

I haven't used `mdl-tooltip--right` yet...

**Comment by egeland** [comment]
Interesting workaround!
A good use for `template replace-part` - I (being a n00b) was wondering where that would be needed.
Thanks for your answer - I'll see how I go with that! :smiley:

**Comment by egeland** [comment]
I tried just changing my tooltip from a `div` to a `label` and it's happy now, so my use case is:

```
<span class="mdl-list__item-secondary-action">
  <button id="edit_${$index}" mdl="button" class="mdl-button--icon mdl-button--colored">
    <i class="mdi mdi-pencil"></i>
  </button>
  <label mdl="tooltip" class="mdl-tooltip--large" for="edit_${$index}">
    Edit Task
  </label>
</span>
```

And yeah, only `--large` works for me..

**Comment by timfish** [comment]
Just hit this and thought I was going crazy!
