### ISSUE TITLE
Example request: How to use a modal?

### ISSUE THREAD

**Issue by egeland** [genadis/aurelia-mdl#8]
I've been looking at the code and the MDL site to try to figure out how to use a modal, but would really love to see an example of a modal used with `aurelia-mdl`..

Would you happen have any example code anywhere?

Thanks! :star:

**Comment by genadis** [comment]
The current MDL implementation is very limiting, at previous versions they had custom implementation with JS component, but recently they switched to using `<dialog>` element which is supported by small number of browsers.

That said, I've used both implementations just fine. But most likely will be switching to other solution for dialogs/modals.

If you still want to give MDL modal a shot, I can send some simple example..

**Comment by egeland** [comment]
I just thought it might be best to stick with MDL, so there are no issues with the theme / styling. But maybe it doesn't matter?

Previously, I've used the modal ([`aurelia-dialog`](https://github.com/aurelia/dialog)) by the Aurelia team, so might stick with that, if you think there's no real value in using the MDL modal..?

**Comment by genadis** [comment]
I realy not in position to make statements regarding MDL modal value :) It worked when I tested on chrome. Check out the browser support http://caniuse.com/#feat=dialog.

If you decide to stick with aurelia dialog you could just use MDL components and styling inside the dialog.
