### ISSUE TITLE
checkbox and switch not updating when bound property changes

### ISSUE THREAD

**Issue by timfish** [genadis/aurelia-mdl#9]
As far as I can tell, the checkbox and switch elements are not updating when the aurelia bound property changes. I've disabled the mdl code and aurelia is checking/unchecking the checkbox but the the `change` event in the mdl code is not being called when being updated programmaticaly. 

I'll conduct some more testing to check I'm not doing anything stupid...

**Comment by genadis** [comment]
Changing property programmaticaly doesn't fire a DOM event. I'm pretty sure if you change DOM property manually using vanilla JS same behavior is expected. When I needed that functionality I just fired event using `dispatchEvent()`.

I know it is an old post.. (wasn't available for while)
